services:
    app.mail:
        class: AppBundle\Service\MailService
        arguments:
            mailer: '@mailer'
            mailer_no_reply: '%mailer_no_reply%'
            mailer_reciever: '%mailer_receiver%'

    app.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments:
            mail_service: '@app.mail'
            router: '@router'
        tags:
            - { name: kernel.event_subscriber }