services:
    app.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments:
            router: '@router'
            mailer: '@mailer'
            mailer_email: '%mailer_user%'
            mailer_reciever: '%mailer_receiver%'
        tags:
            - { name: kernel.event_subscriber }
    app.user_role_listener:
        class: AppBundle\EventListener\UserRoleListener
        arguments:
            mailer: '@mailer'
            mailer_email: '%mailer_user%'
        tags:
            - { name: kernel.event_subscriber }
